config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'postcomments/create'

  get 'postcomments/destroy'

  devise_for :users,:path=>'accounts'
  root 'posts#index'
  resources :users do
    get 'my_profile' => 'posts#my_profile', as: 'my_profile'
    resources :posts do
      resources :postcomments 
    end
  end

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :postcomments
	has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  	validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/png']
    validates :description, presence: true, length: {maximum: 150}

end

app/models/postcomment.rb
class Postcomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: {maximum: 150}
  validates :score, presence: true, numericality: {greater_than: 0,max:5}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :postcomments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
  private
  
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
  	before_action :set_post


def create
  @postcomment = @post.postcomments.build(postcomment_params)
  @postcomment.user_id = current_user.id
  if @postcomment.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  else
    flash[:alert] = "Check the comment form, something went wrong."
    render root_path
  end
end
def destroy
    @postcomment = @post.postcomments.find(params[:id])
    if @postcomment.user_id == current_user.id or @post.user==current_user
      @postcomment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
end
private
def postcomment_params  
  params.require(:postcomment).permit(:content,:score,:user_id,:post_id)
end
def set_post  
  @post = Post.find(params[:post_id])
end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	
  	def index
    	@posts = Post.paginate(:page => params[:page], :per_page => 10).order('id DESC') 
  	end
  
  	def show  
  		@post = Post.find(params[:id])
  	end 
  	

 

  	def my_profile
    
	    @user=User.find(params[:user_id])
	    #@posts=@user.posts.all
	    @posts = @user.posts.paginate(:page => params[:page], :per_page => 10).order('id DESC')
	    @post=Post.new
    
  	end

  	def new
		@user=User.find(params[:user_id])
		@post = Post.new
  	end

	def create  
  		@post = Post.create(post_params)
  		redirect_to user_posts_path
	end 

	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to :back		
	end

	def edit
		@post = Post.find(params[:id])
		
	end
	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to root_url
		
	end
	

private


def post_params
	params.require(:post).permit(:image, :description, :user_id,:postcomment_id)
end
def set_post  
	@post = Post.find(params[:post_id])
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	    @user=User.find(params[:id])
	    @posts=@user.posts.order(created_at: :DESC)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kontrsent</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	



	<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photo Gallery", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="navbar-nav navbar-right">
        
          <% if user_signed_in? %>
            <li class="navbar-text">
              Hello, <%= link_to truncate(current_user.name,length:9), edit_user_registration_path(current_user), class: 'navbar-link' %>
            </li>
            
            <li class="navbar-text">
              <%= link_to 'My profile',user_my_profile_path(current_user) %>
            </li>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to 'Admin Panel', admin_root_path %></li>
                <% end %>
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% else %>
            <%= link_to 'Register', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </ul>
      
    </div>
  </div>
</nav>







<%= yield %>

</body>
</html>

app/views/postcomments/_postcomment.html.erb
<%if user_signed_in? %>
  <div class="user-name">
    <%= link_to postcomment.user.name, user_path(postcomment.user) %>
  </div>
<%end %>
<div class="comment-content">

  <%= postcomment.content %>
  <%= postcomment.score %>
  <div class="text-right">
      <% if current_user== postcomment.user || post.user==current_user %>
        <%= link_to user_post_postcomment_path(post.user,post, postcomment), method: :delete, data: { confirm: "Are you sure?" } ,remote: true do %>
          <span class="glyphicon glyphicon-remove delete-comment"></span>
        <% end %>
      <% end %>
  </div>    
</div>
          
       

app/views/postcomments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'postcomments/postcomment', post: @post, postcomment: @postcomment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/postcomments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.postcomments, post: @post, postcomment: @postcomment %>");	

app/views/posts/_form.html.erb
<div class="form-wrapper">
<%= form_for [current_user, @post], html: {class: 'form-horizontal'} do |f| %>

  <div class="form-group text-center">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="form-group text-center">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/posts/_part.html.erb
<div class="comment-content">
   <% avg=0 %>
   <% @post.postcomments.each do |rating|%>

   <% avg+=rating.score %>
   <%end %>
   <%average = avg/@post.postcomments.size.to_f %>
   Average rating is: <%= average.round(2) %>
</div>

app/views/posts/index.html.erb
<%= will_paginate @posts %>
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
  <div class="post">
    <div class="time-ago text-center">      
      <%= time_ago_in_words post.created_at %>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:thumb)), user_post_path(post.user,post)%>
    </div>
    <p class="caption">
      <%= post.description %><br>	
    </p>
    <p>
     by: <%= link_to post.user.name,user_path(post.user) %>
    </p>
  </div>
  <% end %>
</div>

app/views/posts/my_profile.html.erb
<%= @user.name  %>s profile <br>
My photos : <%= link_to 'Create new photo', new_user_post_path(current_user)%>
<%= will_paginate @posts %>
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="image center-block">
        <%= image_tag post.image.url(:medium), class:'img-responsive' %>  
      </div>
      <p class="caption">
        <%= post.description %><br> 
      </p>

      <p>
        <%if current_user == @user%>
          <%= link_to 'Edit',edit_user_post_path(post.user,post) %>
          <%= link_to 'Delete', user_post_path(post.user,post),
            method: :delete,
            data: {confirm: 'Do you want to remove this product?'} %>
        <%end %> 
      </p>
    </div>
  <% end %>
</div>





    

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        <%= @post.user.name %><br>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.description %>
    </p>
    
    <div class="comments" id="comments_<%= @post.id %>">
      <% if @post.postcomments %>
         
      <div class="comment">
      <%= render 'posts/part' %>
        <%= render @post.postcomments.last(3), post: @post %>
      </div>
      <% end %>
    </div>
    <div class="comment-form col-sm-11">
        <%= form_for([@post.user,@post, @post.postcomments.build], remote: true) do |f| %>
          <%= f.select :score,[0,1,2,3,4,5], class: "comment_content", id: "comment_content_#{@post.id}" %>
          <%= f.text_area :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{@post.id}"%>
          <%= f.submit class: 'btn btn-default' %>
        <% end %>
      </div> 
    <div class="text-center">
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
 
<% @posts.each do |post| %>
  <div class="post">
      <div class="post-head">
        <div class="name">
          <h6><%= post.user.name %> <br></h6>
          <%if @user == current_user%>
          <%= link_to 'Edit profile', edit_user_registration_path(current_user) %>
           <%end %> 
        </div>
      </div>
      <div class="image center-block">
      <%= image_tag post.image.url(:medium), class:'img-responsive' %> 
      </div>
      <p class="caption">
        <%= post.description %><br> 
      </p>
      <p>
        <%if @user == current_user%>
              <%= link_to 'Edit',edit_user_post_path(post.user,post) %>
              <%= link_to 'Delete',user_post_path(post.user,post),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        <%end %> 
      </p>
    </div>
  <% end %>